#docker stack deploy -c .\mssql_docker_container.yaml <instance-name>

version: "3"
services:
  db: 
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    networks:
      - mssql_network
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=WFgDlSTs8fZ6Qf0J7ivo
      - MSSQL_PID=Express
    restart: unless-stopped
    ports:
      - "1404:1433"
    volumes:
      - "test_mssql:/var/opt/mssql"
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  test_mssql:
    external: true
networks:
  mssql_network: