version: "3"
services:
  db: 
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    networks:
      - mssql_network
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=WFgDlSTs8fZ6Qf0J7ivo
      - MSSQL_PID=Express
    restart: unless-stopped
    ports:
      - "1402:1433"
    volumes:
      - "mssql_volume:/var/opt/mssql"
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  mssql_volume:
networks:
  mssql_network: